<a href="https://colab.research.google.com/github/r-hopper/hema/blob/main/Rapier_Thrust_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Rapier Thrust Data Processing for Power Analysis

In [ ]:
# Load libraries and packages

import os
import glob
import numpy as np
from numpy import r_
import pandas as pd
import math
import re
import matplotlib.pyplot as plt
import bokeh
import seaborn as sns
plt.style.use('ggplot')
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
# Upload raw txt files into the Colab environment to run
# You will have to do this every time since files get deleted when the runtime gets recycled
# Raw data lives here: https://drive.google.com/drive/folders/1tFzOpPPhSLQ8DmdO2GmTLWJ46TG2pkPO?usp=share_link

# Directories
directory = ['mike', 'ethan', 'patrick', 'derek']
# Parent Directory path
parent_dir = "/content"


# Set paths and make directories
for d in directory:
  path = os.path.join(parent_dir,d)
  os.mkdir(path)
  print("Directory '% s' created" % d)


# NOW UPLOAD THE RELEVANT RAW FILES INTO EACH OF THESE DIRECTORIES
# YOU CANNOT SKIP THIS STEP

Directory 'a' created
Directory 'b' created
Directory 'c' created
Directory 'd' created

# Mike O'Brien Rapier Data

In [ ]:
# We're gonna concatenate all of the mike trials together before we calculate acceleration

path = r'/content/mike' # path to files

# Get the files from the path provided in the OP
files = Path(path).glob('*.txt')  # .rglob to get subdirectories

mike_dfs = list()
for f in files:
    data = pd.read_csv(f, sep=";")
    # .stem is method for pathlib objects to get the filename w/o the extension
    data['file'] = f.stem
    mike_dfs.append(data)

mike_df = pd.concat(mike_dfs, ignore_index=True)

In [ ]:
mike_df.head()

   index         x         y         z                    file
0      0  0.005753 -0.983398 -0.185410  mike_pike_steel_trial3
1      1  0.013260 -0.985718 -0.180725  mike_pike_steel_trial3
2      2  0.014114 -0.981461 -0.195663  mike_pike_steel_trial3
3      3  0.006607 -0.979874 -0.205795  mike_pike_steel_trial3
4      4  0.006485 -0.983780 -0.191818  mike_pike_steel_trial3

#### Calculate force in Gs
#### magnitude of a vector |M| = sqrt(x^2 + y^2 + z^2)

In [ ]:
force = np.sqrt((mike_df.iloc[:,1]**2) + (mike_df.iloc[:,2]**2) + (mike_df.iloc[:,3]**2)) # calculate |F| using x,y,z
mike_df['force']=force

In [ ]:
mike_df.head()

   index         x         y         z                    file     force
0      0  0.005753 -0.983398 -0.185410  mike_pike_steel_trial3  1.000741
1      1  0.013260 -0.985718 -0.180725  mike_pike_steel_trial3  1.002236
2      2  0.014114 -0.981461 -0.195663  mike_pike_steel_trial3  1.000874
3      3  0.006607 -0.979874 -0.205795  mike_pike_steel_trial3  1.001273
4      4  0.006485 -0.983780 -0.191818  mike_pike_steel_trial3  1.002327

#### Extract tip material text

In [ ]:
# initializing substrings to extract vetween
#tip = mike_df.file.str.extract((r'(?<=% pike_)(.*)(?= _trial)'), expand=True)

tip = re.search('pike_(.*)_trial', mike_df['file'].astype(str))
print(tip[0:3])

TypeError: ignored

#### Extract participant text

# Ethan Heilman Rapier Data

In [ ]:
# We're gonna concatenate all of the mike trials together before we calculate acceleration

path = r'/content/ethan' # path to files

# Get the files from the path provided in the OP
files = Path(path).glob('*.txt')  # .rglob to get subdirectories

ethan_dfs = list()
for f in files:
    data = pd.read_csv(f, sep=";")
    # .stem is method for pathlib objects to get the filename w/o the extension
    data['file'] = f.stem
    ethan_dfs.append(data)

ethan_df = pd.concat(ethan_dfs, ignore_index=True)

In [ ]:
ethan_df.head()

   index         x         y         z                    file
0      0  0.005753 -0.983398 -0.185410  mike_pike_steel_trial3
1      1  0.013260 -0.985718 -0.180725  mike_pike_steel_trial3
2      2  0.014114 -0.981461 -0.195663  mike_pike_steel_trial3
3      3  0.006607 -0.979874 -0.205795  mike_pike_steel_trial3
4      4  0.006485 -0.983780 -0.191818  mike_pike_steel_trial3

#### Calculate force in Gs
#### magnitude of a vector |M| = sqrt(x^2 + y^2 + z^2)

In [ ]:
force = np.sqrt((ethan_df.iloc[:,1]**2) + (ethan_df.iloc[:,2]**2) + (ethan_df.iloc[:,3]**2)) # calculate |F| using x,y,z
ethan_df['force']=force

In [ ]:
ethan_df.head()

   index         x         y         z                       file     force
0      0  0.091522 -0.992325 -0.113907  ethan_pike_leather_trial4  1.003025
1      1  0.094162 -0.992477 -0.104874  ethan_pike_leather_trial4  1.002435
2      2  0.084534 -0.994843 -0.095383  ethan_pike_leather_trial4  1.002974
3      3  0.078781 -0.996506 -0.081528  ethan_pike_leather_trial4  1.002934
4      4  0.086990 -0.995941 -0.068497  ethan_pike_leather_trial4  1.002077

# Patrick Breitenbach Rapier Data

In [ ]:
# We're gonna concatenate all of the mike trials together before we calculate acceleration

path = r'/content/patrick' # path to files

# Get the files from the path provided in the OP
files = Path(path).glob('*.txt')  # .rglob to get subdirectories

patrick_dfs = list()
for f in files:
    data = pd.read_csv(f, sep=";")
    # .stem is method for pathlib objects to get the filename w/o the extension
    data['file'] = f.stem
    patrick_dfs.append(data)
    
patrick_df = pd.concat(patrick_dfs, ignore_index=True)

In [ ]:
patrick_df.head()

   index         x         y         z                         file
0      0  0.020096 -0.998444 -0.066422  patrick_pike_leather_trial3
1      1  0.019287 -0.999405 -0.035507  patrick_pike_leather_trial3
2      2  0.019424 -0.999954 -0.017120  patrick_pike_leather_trial3
3      3  0.019531 -0.999939 -0.019897  patrick_pike_leather_trial3
4      4  0.017960 -0.999237 -0.051376  patrick_pike_leather_trial3

#### Calculate force in Gs
#### magnitude of a vector |M| = sqrt(x^2 + y^2 + z^2)

In [ ]:
force = np.sqrt((patrick_df.iloc[:,1]**2) + (patrick_df.iloc[:,2]**2) + (patrick_df.iloc[:,3]**2)) # calculate |F| using x,y,z
patrick_df['force']=force

In [ ]:
patrick_df.head()

   index         x         y         z                         file     force
0      0  0.020096 -0.998444 -0.066422  patrick_pike_leather_trial3  1.000853
1      1  0.019287 -0.999405 -0.035507  patrick_pike_leather_trial3  1.000222
2      2  0.019424 -0.999954 -0.017120  patrick_pike_leather_trial3  1.000289
3      3  0.019531 -0.999939 -0.019897  patrick_pike_leather_trial3  1.000328
4      4  0.017960 -0.999237 -0.051376  patrick_pike_leather_trial3  1.000718

# Derek Wise Rapier Data

In [ ]:
# We're gonna concatenate all of the mike trials together before we calculate acceleration

path = r'/content/derek' # path to files

# Get the files from the path provided in the OP
files = Path(path).glob('*.txt')  # .rglob to get subdirectories

derek_dfs = list()
for f in files:
    data = pd.read_csv(f, sep=";")
    # .stem is method for pathlib objects to get the filename w/o the extension
    data['file'] = f.stem
    derek_dfs.append(data)
    
derek_df = pd.concat(derek_dfs, ignore_index=True)

In [ ]:
derek_df.head()

   index         x         y         z                      file
0      0  0.019287 -0.993118 -0.116394  derek_pike_bullet_trial2
1      1  0.024734 -0.995270 -0.101151  derek_pike_bullet_trial2
2      2  0.032562 -0.996384 -0.092896  derek_pike_bullet_trial2
3      3  0.039398 -0.996811 -0.095840  derek_pike_bullet_trial2
4      4  0.041870 -0.995026 -0.106949  derek_pike_bullet_trial2

#### Calculate force in Gs
#### magnitude of a vector |M| = sqrt(x^2 + y^2 + z^2)

In [ ]:
force = np.sqrt((derek_df.iloc[:,1]**2) + (derek_df.iloc[:,2]**2) + (derek_df.iloc[:,3]**2)) # calculate |F| using x,y,z
derek_df['force']=force

In [ ]:
derek_df.head()

   index         x         y         z                      file     force
0      0  0.019287 -0.993118 -0.116394  derek_pike_bullet_trial2  1.000101
1      1  0.024734 -0.995270 -0.101151  derek_pike_bullet_trial2  1.000703
2      2  0.032562 -0.996384 -0.092896  derek_pike_bullet_trial2  1.001235
3      3  0.039398 -0.996811 -0.095840  derek_pike_bullet_trial2  1.002182
4      4  0.041870 -0.995026 -0.106949  derek_pike_bullet_trial2  1.001633